name: chrono
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
services:
  chrono:
    build:
      args:
        APT_DEPENDENCIES: python3.10 python3.10-dev python3-pip libirrlicht-dev libeigen3-dev
          git cmake cmake-curses-gui libglu1-mesa-dev mesa-common-dev swig libglew-dev
          freeglut3-dev libglfw3 libglfw3-dev x11proto-gl-dev libxxf86vm-dev openmpi-common
          libopenmpi-dev ninja-build python3-numpy libhdf5-dev ros-${ROS_DISTRO}-ros-base
          python3-colcon-common-extensions libfastcdr-dev libfastrtps-dev libglew-dev
        CUDA_VERSION: 13.2.1
        OPTIX_ARCHIVE: sensor-dep.zip
        PROJECT: ${COMPOSE_PROJECT_NAME}
        ROS_DISTRO: ${ROS_DISTRO}
        UBUNTU_VERSION: '22.04'
        USER_GID: '1000'
        USER_UID: '1000'
      context: ./docker/chrono
      dockerfile: ./chrono.dockerfile
      network: host
    container_name: ${COMPOSE_PROJECT_NAME}-orb
    environment:
      DISPLAY: ${DISPLAY:-}
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      XAUTHORITY: /home/${ATK_CONTAINER_USERNAME}/.Xauthority
      XDG_RUNTIME_DIR: /tmp/runtime-${ATK_CONTAINER_USERNAME}
    gpus: all
    hostname: ${COMPOSE_PROJECT_NAME}-orb
    image: atk/${COMPOSE_PROJECT_NAME}:orb
    ipc: host
    network_mode: host
    shm_size: 6g
    tty: true
    volumes:
    - bind:
        create_host_path: true
      source: ./${MOUNT_DIR}
      target: /home/${ATK_CONTAINER_USERNAME}/${MOUNT_DIR}
      type: bind
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${HOME}/.Xauthority:/tmp/host.XAuthority:ro
    working_dir: /home/${ATK_CONTAINER_USERNAME}/${MOUNT_DIR}/chrono
  vnc:
    build:
      args:
        RUN_FLUXBOX: 'yes'
        RUN_XTERM: 'yes'
        VNC_PASSWORD: ${COMPOSE_PROJECT_NAME}
      context: ./docker/vnc
      dockerfile: ./vnc.dockerfile
      network: host
    container_name: ${COMPOSE_PROJECT_NAME}-vnc
    environment:
      DISPLAY: ${DISPLAY:-}
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      RUN_FLUXBOX: 'yes'
      RUN_XTERM: 'no'
      XAUTHORITY: /home/${ATK_CONTAINER_USERNAME}/.Xauthority
      XDG_RUNTIME_DIR: /tmp/runtime-${ATK_CONTAINER_USERNAME}
    gpus: all
    hostname: ${COMPOSE_PROJECT_NAME}-vnc
    image: atk/${COMPOSE_PROJECT_NAME}:vnc
    network_mode: host
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      published: 8080-8099
      target: 8080
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      published: 5900-5999
      target: 5900
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${HOME}/.Xauthority:/tmp/host.XAuthority:ro
x-optionals:
  gpus:
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    gpus: all
  network_mode_host:
    network_mode: host
  x11:
    environment:
      DISPLAY: ${DISPLAY:-}
      XAUTHORITY: /home/${ATK_CONTAINER_USERNAME}/.Xauthority
      XDG_RUNTIME_DIR: /tmp/runtime-${ATK_CONTAINER_USERNAME}
    network_mode: host
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${HOME}/.Xauthority:/tmp/host.XAuthority:ro
