x-optionals:
  gpus:
    gpus: all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
  network_mode_host:
    network_mode: 'host'
  x11:
    network_mode: 'host'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '${HOME}/.Xauthority:/tmp/host.XAuthority:ro'
    environment:
      DISPLAY: ${DISPLAY:-}
      XAUTHORITY: /home/${ATK_CONTAINER_USERNAME}/.Xauthority
      XDG_RUNTIME_DIR: /tmp/runtime-${ATK_CONTAINER_USERNAME}
name: chrono
services:
  chrono:
    image: 'atk/${COMPOSE_PROJECT_NAME}:test'
    hostname: '${COMPOSE_PROJECT_NAME}-test'
    container_name: '${COMPOSE_PROJECT_NAME}-test'
    shm_size: "6g"
    ipc: host
    build:
      context: './docker/chrono'
      network: 'host'
      dockerfile: './chrono.dockerfile'
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
        CUDA_VERSION: '13.0.0'
        UBUNTU_VERSION: '22.04'
        USER_UID: '1001'
        USER_GID: '1001'
        OPTIX_SCRIPT: NVIDIA-OptiX-SDK-9.0.0-linux64-x86_64.sh
        ROS_DISTRO: ${ROS_DISTRO}
        APT_DEPENDENCIES: 'python3.10 python3.10-dev python3-pip libirrlicht-dev libeigen3-dev git cmake cmake-curses-gui libglu1-mesa-dev mesa-common-dev swig libglew-dev freeglut3-dev libglfw3 libglfw3-dev x11proto-gl-dev libxxf86vm-dev openmpi-common libopenmpi-dev ninja-build python3-numpy ros-${ROS_DISTRO}-ros-base python3-colcon-common-extensions libfastcdr-dev libfastrtps-dev libglew-dev'

    environment:
      DISPLAY: ${DISPLAY:-vnc:0.0}
    working_dir: '/home/${ATK_CONTAINER_USERNAME}/${MOUNT_DIR}/chrono'
    tty: true
    volumes:
    - ./${MOUNT_DIR}:/home/${ATK_CONTAINER_USERNAME}/${MOUNT_DIR}
  vnc:
    image: 'atk/${COMPOSE_PROJECT_NAME}:vnc'
    hostname: '${COMPOSE_PROJECT_NAME}-vnc'
    container_name: '${COMPOSE_PROJECT_NAME}-vnc'
    build:
      context: './docker/vnc'
      dockerfile: './vnc.dockerfile'
      network: 'host'
      args:
        VNC_PASSWORD: '${COMPOSE_PROJECT_NAME}'
        RUN_XTERM: 'yes'
        RUN_FLUXBOX: 'yes'
    environment:
      RUN_XTERM: no
      RUN_FLUXBOX: yes
    ports:
      - '127.0.0.1:8080-8099:8080'
      - '127.0.0.1:5900-5999:5900'
networks:
  default:
    name: '${COMPOSE_PROJECT_NAME}'
